### ISSUE TITLE
Parse all feed meta properties

### ISSUE THREAD

**Issue by rowanmanning** [rowanmanning/feed-parser#18]
The following stuff needs to be parsed out (using [gofeed](https://github.com/mmcdole/gofeed#default-mappings) as a reference):

- [ ] `authors` - an array of author objects (`name`, `email`, `url` properties)
- [ ] `categories` - an array of category objects (`term`, `scheme`, `label` properties?)
- [ ] `copyright` - a string of copyright information
- [x] `description` - a string describing the feed
- [x] `self` - a URL pointing to the feed itself
- [ ] `generator` - a generator object (`url`, `version`, `label` properties)
- [ ] `image` - an image object (`url`, `description`, `width`, `height` properties)
- [x] `language` - a string language code
- [x] `link` - a URL pointing to an HTML representation of the feed
- [x] `published` - a string date indicating when the feed was published
- [x] `title` - a string title of the feed
- [x] `updated` - a string date indicating when the feed was last updated
